[window]
position = {x = 0, y = 0}
padding = {x = 0, y = 0}
decorations = "Buttonless" # Buttonless, None, Transparent, Full
opacity = 1
blur = false
startup_mode = "Maximized"
title="Terminal"
decorations_theme_variant = "Dark"
[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size=15
[colors]
vi_mode_cursor = { text = "#000000", cursor = "#ffffff" }
transparent_background_colors = true
[mouse]
hide_when_typing = true
